apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: web
    image: evgeniim/web
    resources:
      limits:
        memory: "100Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
