backend:
  type: es
  es:
    host: elasticsearch-master
rawConfig: |
  @INCLUDE
  @INCLUDE
  @INCLUDE
  @INCLUDE
  fluent-bit-service.conf fluent-bit-input.conf fluent-bit-filter.conf fluent-bit-output.conf
  
  [FILTER]
      Name    modify
      Match   *
      Remove  time
      Remove  @timestamp
